mbta_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "../data/mbta.duckdb"
      schema: raw_mbta
      threads: 4
    ci:
      type: duckdb
      path: ":memory:"
      schema: raw_mbta
      threads: 4
    prod:
      type: bigquery
      method: service-account
      project: server-i3
      dataset: raw_mbta
      keyfile: /opt/airflow/keys/mbta-sa-key.json
      threads: 4
      location: US